name: Build Arch Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Remove .SRCINFO before the action runs to avoid permission issues
      - name: Clean up .SRCINFO
        run: |
          if [ -f .SRCINFO ]; then
            rm -f .SRCINFO
          fi

      # Run Arch Linux packaging action inside container
      - name: Run Arch Package Action
        uses: heyhusen/archlinux-package-action@v2.2.1
        with:
          path: /
          flags: -si --noconfirm
          namcap: true
          srcinfo: true
          updpkgsums: false
          aur: false
          update_archlinux_keyring: true
