name: Build Arch Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Optional: Make .SRCINFO writable if it exists
      - name: Make .SRCINFO writable
        run: |
          if [ -f .SRCINFO ]; then
            chmod +w .SRCINFO
          fi

      # Optional: Remove .SRCINFO to avoid permission issues
      - name: Remove existing .SRCINFO
        run: rm -f .SRCINFO

      # Let the Arch package action handle .SRCINFO generation
      - name: Run Arch Package Action
        uses: heyhusen/archlinux-package-action@v2.2.1
        with:
          path: /
          flags: -si --noconfirm
          namcap: true
          srcinfo: true
          updpkgsums: false
          aur: false
          update_archlinux_keyring: true
